VERTALINGEN = {
    "standaard": "Standaard",
    "status_wijziging": "Status wijziging",
    "melding_aangemaakt": "Melding aangemaakt",
    "taakopdracht_aangemaakt": "Taakopdracht aangemaakt",
    "taakopdracht_status_wijziging": "Taakopdracht status wijziging",
    "opgelost": "Opgelost",
    "niet_opgelost": "Niet opgelost",
    "aangemaakt": "Aangemaakt",
    "gewijzigd": "Gewijzigd",
    "verwijderd": "Verwijderd",
    "verwijderd": "Verwijderd",
    "in_behandeling": "In behandeling",
    "openstaand": "Openstaand",
    "controle": "Controle",
    "afgehandeld": "Afgehandeld",
    "nieuw": "Nieuw",
    "bezig": "Bezig",
    "voltooid": "Voltooid",
    "adres": "Adres",
    "lichtmast": "Lichtmast",
    "graf": "Graf",
    "vak": "Vak",
    "fotos": "Foto's",
    "aannemer": "Aangenomen door",
    "no_email": "De melder beschikt niet over een e-mailadres.",
    "grafnummer": "Grafnummer",
    "naam_melder": "Naam",
    "toelichting": "Toelichting",
    "email_melder": "E-mailadres",
    "begraafplaats": "Begraafplaats",
    "rechthebbende": "Is deze persoon de rechthebbende of belanghebbende?",
    "specifiek_graf": "Betreft het verzoek een specifiek graf?",
    "naam_overledene": "Naam overledene",
    "telefoon_melder": "Telefoonnummer",
    "terugkoppeling_gewenst": "Is terugkoppeling gewenst?",
}
